{
  "openapi": "3.0.0",
  "info": {
    "title": "Adasky API (Automotive)",
    "description": "API to perform Automotive operations",
    "contact": {
      "email": "support@adasky.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/{{apiPath}}",
      "description": "Server on /api for camera 1 and on /api2 for camera 2"
    }
  ],
  "tags": [
    {
      "name": "main",
      "description": "Operations related to the main screen"
    },
    {
      "name": "preview",
      "description": "Operations related to the preview window"
    },
    {
      "name": "record",
      "description": "Operations for recording to external disk"
    },
    {
      "name": "v2i",
      "description": "Configuration related to ethernet communication streaming"
    },
    {
      "name": "detector",
      "description": "Operations related to the Detector"
    },
    {
      "name": "static_shutter",
      "description": "Operations related to the static shutter"
    },
    {
      "name": "application",
      "description": "Operations related to the application managment"
    }
  ],
  "paths": {
    "/static_shutter/settings": {
      "get": {
        "tags": [
          "static_shutter"
        ],
        "summary": "static shutter settings",
        "description": "get static shutter",
        "operationId": "get_static_shutter",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StaticShutter"
                }
              }
            }
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.static_shutter_controller"
      },
      "post": {
        "tags": [
          "static_shutter"
        ],
        "summary": "static shutter settings",
        "description": "set static shutter",
        "operationId": "set_static_shutter",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/StaticShutter"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success"
          },
          "400": {
            "description": "invalid"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.static_shutter_controller"
      }
    },
    "/record/profile": {
      "get": {
        "tags": [
          "record"
        ],
        "summary": "Get recording profile",
        "description": "Get recording profile and parameters",
        "operationId": "get_recording_profile",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecordingProfile"
                }
              }
            }
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.record_controller"
      },
      "post": {
        "tags": [
          "record"
        ],
        "summary": "set a recording profile",
        "description": "set one of the recording profiles - All, Production, Minimal. This command should not be used during recording",
        "operationId": "set_recording_profile",
        "requestBody": {
          "content": {
            "application/text": {
              "schema": {
                "$ref": "#/components/schemas/RecordingMode"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "profile was set"
          },
          "400": {
            "description": "invalid"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.record_controller"
      }
    },
    "/record/state": {
      "get": {
        "tags": [
          "record"
        ],
        "summary": "Get recording state",
        "description": "Get recording state parameters",
        "operationId": "get_recording_state",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecordingState"
                }
              }
            }
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.record_controller"
      },
      "post": {
        "tags": [
          "record"
        ],
        "summary": "start or stop recording",
        "description": "start or stop recording based on current system status. Note that only `is_recording` field is relevant in this version.",
        "operationId": "set_recording_state",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RecordingState"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success"
          },
          "400": {
            "description": "invalid"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.record_controller"
      }
    },
    "/application/control": {
      "summary": "Application control",
      "description": "Returns Application status object",
      "get": {
        "tags": [
          "application"
        ],
        "summary": "Get application Status",
        "description": "Get application Status",
        "operationId": "get_application_status",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Status"
                }
              }
            }
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.application_controller"
      }
    },
    "/application/detailed_logs": {
      "get": {
        "tags": [
          "application"
        ],
        "summary": "Get detailed logs",
        "description": "Returns a .7z file to be sent to Adasky",
        "operationId": "get_detailed_logs",
        "responses": {
          "102": {
            "description": "The log .7z file is not ready yet"
          },
          "200": {
            "description": "A .7z file",
            "content": {
              "application/x-7z-compressed": {
                "schema": {
                  "type": "string",
                  "format": "binary",
                  "x-content-type": "application/x-7z-compressed"
                }
              }
            }
          },
          "400": {
            "description": "invalid"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.application_controller"
      },
      "post": {
        "tags": [
          "application"
        ],
        "summary": "Generate detailed logs",
        "description": "Only generate the log files to be downloaded later",
        "operationId": "generate_detailed_logs",
        "responses": {
          "201": {
            "description": "response was set"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.application_controller"
      }
    },
    "/main/components": {
      "get": {
        "tags": [
          "main"
        ],
        "summary": "Get available components",
        "description": "Returns a list of all visible components",
        "operationId": "get_components",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Components"
                  },
                  "x-content-type": "application/json"
                }
              }
            }
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.main_controller"
      }
    },
    "/main/about": {
      "get": {
        "tags": [
          "main"
        ],
        "summary": "Get version",
        "description": "Returns a string per versioned item",
        "operationId": "get_about",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/About"
                }
              }
            }
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.main_controller"
      }
    },
    "/main/userconfig": {
      "post": {
        "tags": [
          "main"
        ],
        "summary": "Update user config",
        "description": "Update user json configuration. This command takes effect only after application restart.",
        "operationId": "update_user_config",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserConfig"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.main_controller"
      }
    },
    "/main/userconfig/{extension}": {
      "get": {
        "tags": [
          "main"
        ],
        "summary": "Get user config",
        "description": "Returns user json configuration",
        "operationId": "get_user_config",
        "parameters": [
          {
            "name": "extension",
            "in": "path",
            "description": "Extension config for get config",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "x-content-type": "application/json"
                }
              }
            }
          }
        },
        "x-openapi-router-controller": "swaggerswagger_server_self_eval_server.controllers.main_controller"
      },
      "delete": {
        "tags": [
          "main"
        ],
        "summary": "Remove user config",
        "description": "Remove user json configuration. This command takes effect only after application restart.",
        "operationId": "remove_user_config",
        "parameters": [
          {
            "name": "extension",
            "in": "path",
            "description": "Extension config to delete. Use '*' for all extensions (a.k.a factory reset)",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.main_controller"
      }
    },
    "/preview/hotkeys": {
      "post": {
        "tags": [
          "preview"
        ],
        "summary": "Various operations to control the provided preview stream",
        "description": "Shift+H                       Show this screen\n\nShift+F                       Vertical Flip\n\nShift+C                       Draw cross\n\nShift+A                       Zoom/Pan reset\n\nShift+Z, Shift+Ctrl+Z         Zoom In/Out\n\nMouse Wheel                   Zoom In/Out\n\nArrows                        Pan right/left/up/down\n\nShift+R                       Draw ROI\n\nShift+D                       Draw Date & Time\n\nShift+W                       World Position\n\nShift+X                       Draw X=0 Line\n\nShift+T                       Draw calibration\n\nBounding Box (bb) controls:\n\n1                             display bb only\n\n2                             display bb coordinates\n\n3                             display bb width-height\n\n4                             display image-related bb info\n\n5                             display position-related bb info (if applicable)\n\nShift+L, Shift+Ctrl+L         BB width wider/thinner\n",
        "operationId": "hotkeys",
        "requestBody": {
          "content": {
            "application/text": {
              "schema": {
                "$ref": "#/components/schemas/Hotkeys"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "key was set"
          },
          "400": {
            "description": "invalid"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.preview_controller"
      }
    },
    "/v2i/settings": {
      "get": {
        "tags": [
          "v2i"
        ],
        "summary": "get v2i settings",
        "description": "get detinations parameters + enable/disable",
        "operationId": "get_v2i_settings",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/V2iSettings"
                }
              }
            }
          },
          "400": {
            "description": "invalid"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.v2i_controller"
      },
      "post": {
        "tags": [
          "v2i"
        ],
        "summary": "set v2i settings",
        "description": "set destinations parameters + enable/disable",
        "operationId": "set_v2i_settings",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/V2iSettings"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "profile was set"
          },
          "400": {
            "description": "invalid"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.v2i_controller"
      }
    },
    "/detector/settings": {
      "get": {
        "tags": [
          "detector"
        ],
        "summary": "detector settings",
        "description": "get detector settings",
        "operationId": "get_detector_settings",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Detector"
                }
              }
            }
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.detector_controller"
      },
      "post": {
        "tags": [
          "detector"
        ],
        "summary": "detector settings",
        "description": "set detector settings",
        "operationId": "set_detector_settings",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Detector"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success"
          },
          "400": {
            "description": "invalid"
          }
        },
        "x-openapi-router-controller": "swagger_adas.swagger_server.controllers.detector_controller"
      }
    }
  },
  "components": {
    "schemas": {
      "InteractiveMsgBox": {
        "type": "object",
        "properties": {
          "msg": {
            "type": "string"
          },
          "severity": {
            "type": "string"
          },
          "response": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "msg": "msg",
          "severity": "severity",
          "response": [
            "response",
            "response"
          ]
        }
      },
      "Status": {
        "type": "object",
        "properties": {
          "RecordingTime": {
            "type": "integer",
            "format": "int64"
          },
          "FPS": {
            "type": "string"
          },
          "msg": {
            "$ref": "#/components/schemas/InteractiveMsgBox"
          }
        },
        "example": {
          "RecordingTime": 6,
          "FPS": "FPS",
          "msg": "msg",
          "severity": "severity",
          "response": [
            "response",
            "response"
          ]
        }
      },
      "RecordingMode": {
        "type": "string",
        "example": "Production",
        "enum": [
          "All",
          "Production",
          "Minimal"
        ]
      },
      "RecordingState": {
        "type": "object",
        "properties": {
          "recording_path": {
            "type": "string",
            "default": ""
          },
          "time_left": {
            "type": "string",
            "default": ""
          },
          "free_memory": {
            "type": "string",
            "default": ""
          },
          "fps": {
            "type": "string",
            "default": "30"
          },
          "is_recording": {
            "type": "boolean"
          }
        },
        "example": {
          "time_left": "time_left",
          "free_memory": "free_memory",
          "fps": "30",
          "is_recording": true,
          "recording_path": "recording_path"
        }
      },
      "RecordingProfile": {
        "type": "object",
        "properties": {
          "config_name": {
            "type": "string"
          },
          "config_desc": {
            "type": "string"
          },
          "extensions": {
            "$ref": "#/components/schemas/RecordingProfile_extensions"
          },
          "watchdog": {
            "$ref": "#/components/schemas/RecordingProfile_watchdog"
          }
        },
        "example": {
          "config_name": "config_name",
          "extensions": {
            "capture_stream": {
              "preview_frame_format": "PNG",
              "depth": "14bit + 8bit",
              "raw_fps": 30,
              "format": "TAR",
              "stop_on_fail": true,
              "preview_fps": 30,
              "csv_headers": "index,x,y,w,h,rank,classid,track_id,range,position_x,position_y,position_z,trajectory_x,trajectory_y,trajectory_z,speed,cal_conf",
              "raw_frame_format": "RAW",
              "enabled": true
            },
            "preview": true,
            "camera_control": true,
            "monitor": true,
            "v2i": true,
            "detector": true
          },
          "watchdog": {
            "min_minutes_to_save": 5,
            "notify_user": 5,
            "min_scene_num": 2,
            "watchtime": 0,
            "disk_space_warn_mb": 6,
            "disk_space_abort_mb": 1,
            "min_nox_exp": 7
          },
          "config_desc": "config_desc"
        }
      },
      "StaticShutter": {
        "type": "object",
        "properties": {
          "toggle": {
            "type": "boolean",
            "description": "Toggle is Static Shutter On/Off",
            "default": false
          }
        },
        "example": {
          "toggle": true
        }
      },
      "SystemCommand": {
        "type": "string",
        "enum": [
          "RestartApp",
          "Reboot",
          "Shutdown"
        ]
      },
      "Components": {
        "type": "string",
        "enum": [
          "recorder",
          "v2i",
          "system",
          "image_quality",
          "analytics"
        ]
      },
      "Hotkeys": {
        "type": "string",
        "enum": [
          "C",
          "x",
          "R",
          "D",
          "1",
          "2",
          "3",
          "4",
          "5",
          "L",
          "Shift+L",
          "T"
        ]
      },
      "About": {
        "type": "object",
        "properties": {
          "Nox": {
            "type": "string"
          },
          "Viper": {
            "type": "string"
          },
          "SDK": {
            "type": "string"
          },
          "CameraId": {
            "type": "string"
          }
        },
        "example": {
          "Nox": "Nox",
          "Viper": "Viper",
          "SDK": "SDK",
          "CameraId": "CameraId"
        }
      },
      "Destination": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "ip": {
            "type": "string"
          },
          "port": {
            "type": "integer",
            "format": "uint16"
          },
          "enable": {
            "type": "boolean"
          }
        },
        "example": {
          "port": 0,
          "enable": true,
          "ip": "ip",
          "name": "name"
        }
      },
      "V2iSettings": {
        "type": "object",
        "properties": {
          "myself": {
            "$ref": "#/components/schemas/Destination"
          },
          "video": {
            "$ref": "#/components/schemas/Destination"
          },
          "detect": {
            "$ref": "#/components/schemas/Destination"
          }
        },
        "example": {
          "video": {
            "port": 0,
            "enable": true,
            "ip": "ip",
            "name": "name"
          }
        }
      },
      "UpdateUserConfig": {
        "type": "object",
        "properties": {
          "config": {
            "type": "object"
          },
          "extension": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "extension": "extension",
          "password": "password",
          "config": {}
        }
      },
      "RecordingProfile_extensions_capture_stream": {
        "type": "object",
        "properties": {
          "enabled": {
            "type": "boolean"
          },
          "depth": {
            "type": "string",
            "example": "14bit + 8bit"
          },
          "format": {
            "type": "string",
            "example": "TAR"
          },
          "raw_frame_format": {
            "type": "string",
            "example": "RAW"
          },
          "preview_frame_format": {
            "type": "string",
            "example": "PNG"
          },
          "raw_fps": {
            "type": "integer",
            "example": 30
          },
          "preview_fps": {
            "type": "integer",
            "example": 30
          },
          "stop_on_fail": {
            "type": "boolean"
          },
          "csv_headers": {
            "type": "string",
            "example": "index,x,y,w,h,rank,classid,track_id,range,position_x,position_y,position_z,trajectory_x,trajectory_y,trajectory_z,speed,cal_conf"
          }
        },
        "example": {
          "preview_frame_format": "PNG",
          "depth": "14bit + 8bit",
          "raw_fps": 30,
          "format": "TAR",
          "stop_on_fail": true,
          "preview_fps": 30,
          "csv_headers": "index,x,y,w,h,rank,classid,track_id,range,position_x,position_y,position_z,trajectory_x,trajectory_y,trajectory_z,speed,cal_conf",
          "raw_frame_format": "RAW",
          "enabled": true
        }
      },
      "RecordingProfile_extensions": {
        "type": "object",
        "properties": {
          "camera_control": {
            "type": "boolean"
          },
          "detector": {
            "type": "boolean"
          },
          "capture_stream": {
            "$ref": "#/components/schemas/RecordingProfile_extensions_capture_stream"
          },
          "preview": {
            "type": "boolean"
          },
          "monitor": {
            "type": "boolean"
          },
          "v2i": {
            "type": "boolean"
          }
        },
        "example": {
          "capture_stream": {
            "preview_frame_format": "PNG",
            "depth": "14bit + 8bit",
            "raw_fps": 30,
            "format": "TAR",
            "stop_on_fail": true,
            "preview_fps": 30,
            "csv_headers": "index,x,y,w,h,rank,classid,track_id,range,position_x,position_y,position_z,trajectory_x,trajectory_y,trajectory_z,speed,cal_conf",
            "raw_frame_format": "RAW",
            "enabled": true
          },
          "preview": true,
          "camera_control": true,
          "monitor": true,
          "v2i": true,
          "detector": true
        }
      },
      "RecordingProfile_watchdog": {
        "type": "object",
        "properties": {
          "watchtime": {
            "type": "integer"
          },
          "disk_space_warn_mb": {
            "type": "integer"
          },
          "disk_space_abort_mb": {
            "type": "integer"
          },
          "notify_user": {
            "type": "integer"
          },
          "min_minutes_to_save": {
            "type": "integer"
          },
          "min_scene_num": {
            "type": "integer"
          },
          "min_nox_exp": {
            "type": "integer"
          }
        },
        "example": {
          "min_minutes_to_save": 5,
          "notify_user": 5,
          "min_scene_num": 2,
          "watchtime": 0,
          "disk_space_warn_mb": 6,
          "disk_space_abort_mb": 1,
          "min_nox_exp": 7
        }
      },
      "Detector": {
        "type": "object",
        "properties": {
          "Obstacles": {
            "type": "boolean",
            "description": "Obstacles On/Off",
            "default": true
          }
        },
        "example": {
          "Obstacles": false
        }
      }
    }
  }
}